### PR TITLE
MW IOS 12 Create Ready To Book

### PR DESCRIPTION
**Pull request by Vnox**
For testing, simply run the application. Try typing in anything in the
search bar and see how the tableview below changes.

### CODE REVIEW

**Comment by Vnox** [comment]
[MW-IOS-12 Create Ready To Book](https://trello.com/c/enMHhyFZ/17-mw-ios-12-create-ready-to-book)

**Comment by seanippolito** [comment]
I can't accept this merge request, please go back and fix the following issue.
- Replace the textField with the iOS built in UISearchBar or UISearchBarAndSearchDisplayController
- This should fix issues with the current textField and unpredictable behavior.

**Comment by Vnox** [comment]
UISearchBar is used now. : )

**Comment by seanippolito** [comment]
This is much better. Couple of things.
- Lowercase letters should still return words that are capitalized.
- Don't forget to set constraints, the fields aren't centered on iPhone 7.
- The magnifying glass should be on the left, it looks funny in the middle.

**Comment by Vnox** [comment]
Fixed all problems.

**Pull request merged**
