### PR TITLE
Changed UI Textfield to Label, Changed static service pick to dynamic

### PR DESCRIPTION
**Pull request by Vnox**
This pull request contains both card 20 and 21, fixed textfield problem. Also changed static button to a dynamic tableview. So I’ll attach it to both 2 cards. 😂

### CODE REVIEW

**Comment by Vnox** [comment]
[MW-IOS-20 Convert Text Fields To Labels](https://trello.com/c/INZdmvOa/25-mw-ios-20-convert-text-fields-to-labels)

**Comment by Vnox** [comment]
[MW-IOS-21 Convert Service Buttons Format](https://trello.com/c/HKnf2cFp/26-mw-ios-21-convert-service-buttons-format)

**Comment by seanippolito** [comment]
you need to merge with dev before requesting to merge

**Comment by seanippolito** [comment]
JKJK, it looks good for now.

**Pull request merged**
